### ISSUE TITLE
Outdated play services dependency

### ISSUE THREAD

**Issue by joen93** [patloew/RxWear#2]
Hi, it seems that your lib is still using google play services 8.4. 
Any chance you could update it to 9.0.2? 😄

**Comment by patloew** [comment]
Hi, I'll update it with the next release.

However, you need to include the the play services wearable package in your apps anyway, in addition to RxWear. There you can use version 9.0.2 and Gradle will resolve the conflict by using the newer version you declared in your `build.gradle`.
