### ISSUE TITLE
RxWear stops working from a service if battery is below certain level

### ISSUE THREAD

**Issue by maciek252** [patloew/RxWear#8]
I've noticed a very strange thing: after getting below certain battery charge level (on the phone), the communication via RxWear works only if the app on the phone is in the foreground, but no longer works from a background service. Maybe it's not an issue with RxWear but with the Wear configuration?

**Comment by patloew** [comment]
RxWear uses the official Wear APIs. This is either a problem with how background services work on your device (e.g. see Oreo changes in services) or with the Wear API itself.
